// https://elixir.bootlin.com/linux/v6.14.3/source/arch/arm64/include/asm/processor.h#L147

pub const CPUContext = packed struct {
    x19: usize = 0,
    x20: usize = 0,
    x21: usize = 0,
    x22: usize = 0,
    x23: usize = 0,
    x24: usize = 0,
    x25: usize = 0,
    x26: usize = 0,
    x27: usize = 0,
    x28: usize = 0,
    fp: usize = 0,
    pc: usize = 0,
    sp: usize = 0,
};

pub const ThreadContext = packed struct {
    cpu_context: CPUContext,
};

pub const TrapFrame = packed struct {
    x0: usize,
    x1: usize,
    x2: usize,
    x3: usize,
    x4: usize,
    x5: usize,
    x6: usize,
    x7: usize,
    x8: usize,
    x9: usize,
    x10: usize,
    x11: usize,
    x12: usize,
    x13: usize,
    x14: usize,
    x15: usize,
    x16: usize,
    x17: usize,
    x18: usize,
    x19: usize,
    x20: usize,
    x21: usize,
    x22: usize,
    x23: usize,
    x24: usize,
    x25: usize,
    x26: usize,
    x27: usize,
    x28: usize,
    x29: usize,
    x30: usize,
    elr_el1: usize,
    sp_el0: usize,
    spsr_el1: usize,
};
